---
name: Tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby:
          - '3.3'
          - '3.2'
          - '3.1'
          - '3.0'
          - 'head'
          - jruby
          - jruby-head
          - truffleruby
          - truffleruby-head

    steps:
      - uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Update bundler
        env:
          RUBY_VERSION: ${{ matrix.ruby }}
        run: |
          case ${RUBY_VERSION} in
            1.8|1.9|2.0|2.1|2.2)
              gem install bundler -v 1.17.3
            ;;

            2.3|2.4|2.5)
              gem install bundler -v 2.3.27
            ;;

            2.6|2.7)
              gem install bundler -v 2.4.22
            ;;

            3.0)
              gem install bundler -v 2.5.23
            ;;

            truffleruby|truffleruby-head)
              gem install bundler -v 2.5.23
            ;;

            *)
              gem update --system
            ;;
          esac

          bundle install

      - name: Run tests
        run: bin/rspec
